version: '3.4'
services:
  erp-discovery:
    image: dehemart/erp-discovery:latest
    container_name: erp-discovery
    ports:
      - 8761:8761
    environment:
      PORT: 8761
      LOG_EUREKA_TURN: "OFF"
      LOG_DISCOVERY_TURN: "OFF"
