spring:
  application:
    name: erp-discovery

server:
  port: ${PORT:8761}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false

logging:
  level:
    com.netflix.eureka: ${LOG_EUREKA_TURN:OFF}
    com.netflix.discovery: ${LOG_DISCOVERY_TURN:OFF}